## 1. Import All the necessary Libraries

In [1]:
import nltk
import re
import pandas as pd
import numpy as np
from numpy import asarray
from nltk.corpus import stopwords
from collections import Counter
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


## 2. Import data from sheet in Dataframe

In [2]:
df = pd.read_csv('/content/Bank_Statement_dataset.csv')
df

Tran Date  Chq No  ...    Balance  Init. Br
0   18-01-2020     NaN  ...   42914.04       572
1   18-01-2020     NaN  ...    2914.04       572
2   18-01-2020     NaN  ...    2857.34       572
3   18-01-2020     NaN  ...    2542.34       572
4   23-01-2020     NaN  ...   39542.34       572
5   23-01-2020     NaN  ...   48442.34       572
6   23-01-2020     NaN  ...  133442.34       572
7   23-01-2020     NaN  ...   83442.34       572
8   23-01-2020     NaN  ...   53442.34       572
9   24-01-2020     NaN  ...   33442.34       572
10  24-01-2020     NaN  ...   13442.34       572
11  24-01-2020     NaN  ...   24442.34       572
12  24-01-2020     NaN  ...    4442.34       572
13  24-01-2020     NaN  ...     442.34       572
14  27-01-2020     NaN  ...   76442.34       572
15  27-01-2020     NaN  ...   79342.34       572
16  27-01-2020     NaN  ...   79338.39       572
17  27-01-2020     NaN  ...    9338.39       572
18  28-01-2020     NaN  ...    9288.39       572
19  28-01-2020     NaN  ...   68188.39       572
20  28-01-2020     NaN  ...   82688.39       572
21  28-01-2020     NaN  ...   88188.39       572
22  28-01-2020     NaN  ...   88184.44       572
23  28-01-2020     NaN  ...   68178.54       572
24  28-01-2020     NaN  ...   18178.54       572
25  28-01-2020     NaN  ...   14172.64       572
26  28-01-2020     NaN  ...    9172.64       572
27  29-01-2020     NaN  ...     172.64       572
28  30-01-2020     NaN  ...   43972.64       572
29  30-01-2020     NaN  ...   23972.64       572
30  31-01-2020     NaN  ...   18972.64       572
31  31-01-2020     NaN  ...   18973.64       572
32  31-01-2020     NaN  ...  218973.64       572
33  31-01-2020     NaN  ...   68973.64       572
34  31-01-2020     NaN  ...   83973.64       572
35  31-01-2020     NaN  ...   75695.58       572
36  31-01-2020     NaN  ...   55695.58       572
37  31-01-2020     NaN  ...   54189.68       572
38  31-01-2020     NaN  ...   55695.58       572
39  31-01-2020     NaN  ...   54189.68       572
40  31-01-2020     NaN  ...   55695.58       572
41  31-01-2020     NaN  ...   54189.68       572
42  31-01-2020     NaN  ...    4189.68       572
43  31-01-2020     NaN  ...    4169.68       572
44  01-02-2020     NaN  ...    4119.68       572
45  01-02-2020     NaN  ...    4120.68       572
46  01-02-2020     NaN  ...    4121.68       572
47  01-02-2020     NaN  ...    9061.68       572
48  02-02-2020     NaN  ...   77361.68       572
49  02-02-2020     NaN  ...   78561.68       572
50  02-02-2020     NaN  ...   28561.68       572
51  02-02-2020     NaN  ...   36561.68       572
52  02-02-2020     NaN  ...   38561.68       572
53  03-02-2020     NaN  ...     561.68       572

[54 rows x 7 columns]

## 3. Drop the non-contributing columns

In [3]:
df.drop(columns=['Chq No','Init. Br'],inplace=True)

## 4. Fill the empty values in 'Credit' and 'Debit' Card

In [4]:
df['Debit']=df['Debit'].fillna(0)
df['Credit']=df['Credit'].fillna(0)

## 5. Create a Fraud Column with empty values

In [5]:
df["isFraud"] = np.nan

## 6. Classify the Debit and Credit Transactions as Fraud and Non-Fraud

In [6]:
for item in range(len(df)):
  value=df.loc[item,'Credit']
  if value>50000:
    df.loc[item,'isFraud']=1

In [7]:
for item in range(len(df)):
  value=df.loc[item,'Debit']
  if value>50000:
    df.loc[item,'isFraud']=1

In [8]:
df['isFraud']=df['isFraud'].fillna(0)
df

Tran Date  ... isFraud
0   18-01-2020  ...     0.0
1   18-01-2020  ...     0.0
2   18-01-2020  ...     0.0
3   18-01-2020  ...     0.0
4   23-01-2020  ...     0.0
5   23-01-2020  ...     0.0
6   23-01-2020  ...     1.0
7   23-01-2020  ...     0.0
8   23-01-2020  ...     0.0
9   24-01-2020  ...     0.0
10  24-01-2020  ...     0.0
11  24-01-2020  ...     0.0
12  24-01-2020  ...     0.0
13  24-01-2020  ...     0.0
14  27-01-2020  ...     1.0
15  27-01-2020  ...     0.0
16  27-01-2020  ...     0.0
17  27-01-2020  ...     1.0
18  28-01-2020  ...     0.0
19  28-01-2020  ...     1.0
20  28-01-2020  ...     0.0
21  28-01-2020  ...     0.0
22  28-01-2020  ...     0.0
23  28-01-2020  ...     0.0
24  28-01-2020  ...     0.0
25  28-01-2020  ...     0.0
26  28-01-2020  ...     0.0
27  29-01-2020  ...     0.0
28  30-01-2020  ...     0.0
29  30-01-2020  ...     0.0
30  31-01-2020  ...     0.0
31  31-01-2020  ...     0.0
32  31-01-2020  ...     1.0
33  31-01-2020  ...     1.0
34  31-01-2020  ...     0.0
35  31-01-2020  ...     0.0
36  31-01-2020  ...     0.0
37  31-01-2020  ...     0.0
38  31-01-2020  ...     0.0
39  31-01-2020  ...     0.0
40  31-01-2020  ...     0.0
41  31-01-2020  ...     0.0
42  31-01-2020  ...     0.0
43  31-01-2020  ...     0.0
44  01-02-2020  ...     0.0
45  01-02-2020  ...     0.0
46  01-02-2020  ...     0.0
47  01-02-2020  ...     0.0
48  02-02-2020  ...     1.0
49  02-02-2020  ...     0.0
50  02-02-2020  ...     0.0
51  02-02-2020  ...     0.0
52  02-02-2020  ...     0.0
53  03-02-2020  ...     0.0

[54 rows x 6 columns]

## 7. Clean the Particulars column data and create  corpus

In [9]:
nltk.download('stopwords')
ps = PorterStemmer()
corpus = []
for i in range(len(df)):
    review = re.sub('[^a-zA-Z]',' ', df['Particulars'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [10]:
tfidf_v = TfidfVectorizer(max_features=10,ngram_range=(1,3))
X = tfidf_v.fit_transform(corpus).toarray()

## 8. Perform Standardisation on Debit and Credit Columns

In [11]:
X_Trans=df.loc[:,['Debit','Credit']]

In [12]:
X_Trans=asarray(X_Trans)
scaler = StandardScaler()
scaled = scaler.fit_transform(X_Trans)

## 9. Concatenate the Independent features from the Particulars,debit and Credit columns

In [13]:
X=np.concatenate((X,scaled),axis=1)

## 10. Obtain the dependent and independent features

In [14]:
Y=df['isFraud']

In [15]:
print(X.shape)
print(Y.shape)

(54, 12)
(54,)


## 11. Apply Sampling to get the balanced dataset

In [16]:
print('Original dataset shape {}'.format(Counter(Y)))

Original dataset shape Counter({0.0: 47, 1.0: 7})


In [17]:
os =  RandomOverSampler(sampling_strategy=0.6)
X_train_res, y_train_res = os.fit_resample(X, Y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [18]:
print('Sampled dataset shape {}'.format(Counter(y_train_res)))

Sampled dataset shape Counter({0.0: 47, 1.0: 28})


## 12. Split into train and test dataset

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=1)

In [20]:
print(X_train.shape)
print(X_test.shape)

(52, 12)
(23, 12)


## 13. Create models on the Training Dataset

In [21]:
def models(X_train,Y_train):
    #Logistic Regression
    log = LogisticRegression(random_state=0)
    log.fit(X_train,Y_train)
    
    #Decision Tree
    tree = DecisionTreeClassifier(criterion='entropy',random_state=0)
    tree.fit(X_train,Y_train)
    
    #Random Forest Classifier
    forest = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    forest.fit(X_train,Y_train)
    
    #Print the output of training the 3 models
    print("Logistic Regression model result " , log.score(X_train,Y_train))
    print("Decision Tree classifier result " , tree.score(X_train,Y_train))
    print("Random Forest cassifier result " , forest.score(X_train,Y_train))
    
    return log , tree, forest

## 14. Get the result of model for Logistic Regression, Decision Tree, Random Forest using the Train dataset

In [22]:
model = models(X_train,Y_train)

Logistic Regression model result  0.9807692307692307
Decision Tree classifier result  1.0
Random Forest cassifier result  0.9807692307692307


## 15.  Create a model that evaluates Performance Matrix such as
Accuracy of model

Confusion Matrix

Classification Report

In [23]:
def Perf_matrix(model_no):
    cm = confusion_matrix(Y_test,model[model_no].predict(X_test))
    
    TP = cm[0][0]
    TN = cm[1][1]
    FP = cm[0][1]
    FN = cm[1][0]
    
    Accuracy     = (TP+TN)/(TP+TN+FP+FN)
    preds        =     model[model_no].predict(X_test)
    Class_Report = classification_report(Y_test,preds)

    return cm,Accuracy,Class_Report

## 16. Performance Matrix of Logistic Regression Model

In [24]:
cm_log,Acc_log,Report_log = Perf_matrix(0)
print("The Accuracy of unkown dataset for Logistic Regression Model: ",Acc_log)
print('\n')
print("The Classification Report for Logistic Regression Model: \n",Report_log)
print('\n')
print("The Confusion Matrix for Logistic Regression Model: \n",cm_log)

The Accuracy of unkown dataset for Logistic Regression Model:  0.9130434782608695


The Classification Report for Logistic Regression Model: 
               precision    recall  f1-score   support

         0.0       0.87      1.00      0.93        13
         1.0       1.00      0.80      0.89        10

    accuracy                           0.91        23
   macro avg       0.93      0.90      0.91        23
weighted avg       0.92      0.91      0.91        23



The Confusion Matrix for Logistic Regression Model: 
 [[13  0]
 [ 2  8]]


## 17. Performance Matrix of Decision Tree Model

In [25]:
cm_tree,Acc_tree,Report_tree = Perf_matrix(1)
print("The Accuracy of unkown dataset for Decision Tree Model: ",Acc_tree)
print('\n')
print("The Classification Report for Decision Tree Model: \n",Report_tree)
print('\n')
print("The Confusion Matrix for Decision Tree Model: \n",cm_tree)

The Accuracy of unkown dataset for Decision Tree Model:  1.0


The Classification Report for Decision Tree Model: 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        13
         1.0       1.00      1.00      1.00        10

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23



The Confusion Matrix for Decision Tree Model: 
 [[13  0]
 [ 0 10]]


## 18. Performance Matrix of Random Forest Model

In [26]:
cm_forest,Acc_forest,Report_forest = Perf_matrix(2)
print("The Accuracy of unkown dataset for Random Forest Model: ",Acc_forest)
print('\n')
print("The Classification Report for Random Forest Model: \n",Report_forest)
print('\n')
print("The Confusion Matrix for Random Forest Model: \n",cm_forest)

The Accuracy of unkown dataset for Random Forest Model:  0.9130434782608695


The Classification Report for Random Forest Model: 
               precision    recall  f1-score   support

         0.0       0.87      1.00      0.93        13
         1.0       1.00      0.80      0.89        10

    accuracy                           0.91        23
   macro avg       0.93      0.90      0.91        23
weighted avg       0.92      0.91      0.91        23



The Confusion Matrix for Random Forest Model: 
 [[13  0]
 [ 2  8]]
